### PR TITLE
Remove fetch response icon and replace it with text

### PR DESCRIPTION
**Pull request by amit-mb**
Earlier - 
Earlier

Now -
Now

### CODE REVIEW

**Comment by revathskumar** [comment]
can we use the text `Fetch Response`.
otherwise the UI is breaking.

**Comment by amit-mb** [comment]
Is it better to just use `Server Response` ? `Fetch Response` seems vague as it doesn't specify which response.

As it is a button above the `textarea`, i think the users will be able to assume that it fills the textarea with `Server Response`

**Comment by revathskumar** [comment]
or can the label be `Mock Reponse`? Either way we need to fix the UI.

**Comment by revathskumar** [comment]
@amit-mb can you send the latest screenshot?

**Comment by amit-mb** [comment]
@revathskumar this is the screenshot after making the latest commit

Fetch Response

**Pull request merged**
